apiVersion: v1
kind: Service
metadata:
  labels:
    name: acmeair-mongo
  name: acmeair-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: acmeair-mongo
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: acmeair-mongo
  name: acmeair-mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: acmeair-mongo
    spec:
      containers:
      - image: mongo
        name: acmeair-mongo
        ports:
        - name: acmeair-mongo
          containerPort: 27017
          hostPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-web
  labels:
    name: acmeair-web
spec:
  type: NodePort
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    name: acmeair-web
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: acmeair-web
  name: acmeair-web-controller
spec:
  replicas: 2
  selector:
    name: acmeair-web
  template:
    metadata:
      labels:
        name: acmeair-web
    spec:
      containers:
      - image: yanglei99/acmeair-nodejs
        name: acmeair-web
        ports:
        - containerPort: 9080
          name: http-server
        env:
        - name: MONGO_URL
          value: "mongodb://acmeair-mongo:27017/acemair"  