apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: acme-auth
  name: acme-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acme-auth
  template:
    metadata:
      labels:
        app: acme-auth
    spec:
      containers:
      - image: yanglei99/acmeair-nodejs
        name: acme-auth
        ports:
        - name: acme-auth
          containerPort: 9043
        env:
        - name: dbtype
          value: "cloudant"     
        - name: CLOUDANT_URL
          value: "https://YOUR_CLOUDANT_URL"     
        - name: APP_NAME
          value: "authservice_app.js"  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: acme-auth
  name: acme-auth
spec:
  type: LoadBalancer
  ports:
  - port: 3010
    targetPort: 9443
  selector:
    app: acme-auth
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: acme-web
  name: acme-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acme-web
  template:
    metadata:
      labels:
        app: acme-web
    spec:
      containers:
      - image: yanglei99/acmeair-nodejs
        name: acme-web
        ports:
        - name: acme-web
          containerPort: 9080
        env:
        - name: dbtype
          value: "cloudant"     
        - name: CLOUDANT_URL
          value: "https://YOUR_CLOUDANT_URL"     
        - name: AUTH_SERVICE
          value: "acme-auth.default.fellowship.svc.example.com:3010" 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: acme-web
  name: acme-web
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 9080
  selector:
    app: acme-web